<?php

// $Id$
/**
 * @file
 * Provides wrapper functions for the s3 amazon webservices.
 * @todo
 * - cleand up the _video_zencoder_postback_jobs() function
 */
/*
 * Implementation of hook_cron().
 */
if (!defined('VIDEO_RENDERING_PENDING'))
  define('VIDEO_RENDERING_PENDING', 1);
if (!defined('VIDEO_RENDERING_ACTIVE'))
  define('VIDEO_RENDERING_ACTIVE', 5);
if (!defined('VIDEO_RENDERING_COMPLETE'))
  define('VIDEO_RENDERING_COMPLETE', 10);
if (!defined('VIDEO_RENDERING_FAILED'))
  define('VIDEO_RENDERING_FAILED', 20);

/**
 * Implementation of hook_menu().
 */
function video_zencoder_menu() {
  $items = array();
  $items['postback/jobs'] = array(
//    'title' => 'Video',
//    'description' => 'Configure different aspects of the video module and its plugins',
    'page callback' => '_video_zencoder_postback_jobs',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

function _video_zencoder_postback_jobs() {
  // get JSON post data
  $data = file_get_contents("php://input");
//  print_r($data);
  watchdog('zencoder', t('Postback received from the Zencoder Transcoding servers.'));
  // get the file object by zenocder job id
  $video = json_decode($data);
//  print_r($zc);
//  $zc_job_id = $video->job->id;
  $zc_job_state = trim($video->job->state);
//  $zc_output_id = $video->output->id;
  $zc_output_state = trim($video->output->state);
//  $zc_output_url = $video->output->url;
  if ($zc_output_state == 'finished' && $zc_job_state == 'finished')
    $video->output->state = VIDEO_RENDERING_COMPLETE;
  if ($zc_output_state == 'failed' || $zc_job_state == 'failed')
    $video->output->state = VIDEO_RENDERING_FAILED;

  // update the Zencoder Job
  module_load_include('inc', 'video_zencoder', '/includes/zencoder');
  $zc = new video_zencoder_api;
  // Lets run delete.
  if ($zc->update($video) && $video->output->state == VIDEO_RENDERING_COMPLETE) {
    $video = $zc->load_job($video->job->id);
    db_query("UPDATE {node} SET status=%d WHERE nid=%d", 1, $video->nid);
    // update the thumbanils
  }
  watchdog('zencoder', t('Updated the Zencoder Job !id to states !states.', array('!id' => $video->job->id, '!states' => $zc_output_state)));
}

/**
 * Implementation of hook_mail().
 */
function video_zencoder_mail($key, &$message, $params) {
  $language = $message['language'];
  $message['subject'] .= 'Zencoder Registration Details for Drupal Video';
  $message['body'][] = video_zencoder_mail_default($params);
}

function video_zencoder_mail_default($params) {
  return t(
      'Welcome to Zencoder for Drupal
-------------------------------

Your account has been created and is ready to start processing.

Your account details are as below.

API Key : %api_key
Password : %password

* Login URL: https://app.zencoder.com/login

You can get help at the following places:

* Our chat room at http://zencoder.com/chat
* Customer forums at https://help.zencoder.com/forums
* The help desk at https://help.zencoder.com/tickets/new

We\'d love to hear from you. Let us know how we can help. Thanks!

Thanks,
-Zencoder for Drupal Team', array('%api_key' => $params['api_key'], '%password' => $params['password']));
}

